project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from techei.views import register,institution,individual
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('', register.HomeView, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('techei/', include('techei.urls')),
    path('accounts/signup/', register.SignUpView.as_view(), name='signup'),
    path('accounts/login/', register.LoginView.as_view(), name='login'),
    path('accounts/login/home/', register.HomeView, name='home'),
    path('accounts/signup/individual/', individual.IndividualSignUpView.as_view(), name='individual_signup'),
    path('accounts/signup/institution/', institution.InstitutionSignUpView.as_view(), name='institution_signup'),
    path('individual_profile', individual.IndividualProfileView, name='individual_profile'),
    path('institution_profile', institution.InstitutionProfileView, name='institution_profile'),
    path('ajax/load-cities/', individual.load_cities, name='ajax_load_cities'),
    #path('individual_dashboard', individual.IndividualDashboardView, name='individual_dashboard'),
    #path('institution_dashboard', institution.InstitutionDashboardView, name='institution_dashboard'),
    path('accounts/signup/institution/', institution.InstitutionSignUpView.as_view(), name='institution_signup'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/techei/urls.py
from django.urls import path
from techei.views import register,institution,individual

urlpatterns =[
    path('eventtype', institution.EventType.as_view(), name='event_type'),
    path('addevent/<int:type>/', institution.AddEvent, name='add_event'),
    path('addfest/', institution.AddFestClubView, name='add_fest'),
    path('festimage/',institution.FestImageView, name='add_fest_image'),
    path('eventimage/',institution.EventImageView, name='add_event_image'),
    path('apply/<int:event_id>/', individual.ApplyEvent, name='apply_event'),
    path('response/',institution.ResponseView, name='response'),
    path('enrolledevents/',individual.EnrolledView, name='enrolled_events'),
]

project/techei/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
import os



# Create your models here.

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('fest/', filename)

def get_file_path_event(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('event/', filename)

class State(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class User(AbstractUser):
    is_individual = models.BooleanField(default=False)
    is_institution = models.BooleanField(default=False)
    is_confirm = models.BooleanField(default=False)


class IndividualProfile(models.Model):
    TYPE=(
        ('0','Student'),
        ('1','Professional'),
        ('2','Other'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    college = models.CharField(max_length=50)
    contact = models.CharField(max_length=15)
    location = models.CharField(max_length=15)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    type = models.CharField(max_length=50, choices=TYPE)
    age= models.IntegerField()

    def __str__(self):
        return self.user.username


class InstitutionProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    institutionname = models.CharField(max_length=50)
    contact = models.CharField(max_length=15)
    location = models.CharField(max_length=15)
    regno = models.IntegerField()
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    rating = models.IntegerField(null=True)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class FestClubModel(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class EventModel(models.Model):
    ATYPE=(
        (0,'Student'),
        (1,'Professional'),
        (2,'Other'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    venue = models.CharField(max_length=100)
    address = models.TextField(max_length=200)
    time = models.TimeField(max_length=15)
    start_date = models.DateField(max_length=15)
    end_date = models.DateField(max_length=15)
    seats = models.IntegerField()
    fee = models.IntegerField(null=True,blank=True)
    prize = models.IntegerField(null=True,blank=True)
    paylink = models.CharField(null=True,max_length=100,blank=True)
    fest = models.ForeignKey(FestClubModel, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    attendee_type = models.IntegerField(choices=ATYPE)
    event_type = models.IntegerField()

    def __str__(self):
        return self.title

class FestImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fest = models.ForeignKey(FestClubModel, on_delete=models.CASCADE)
    name = models.ImageField(upload_to=get_file_path ,max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class EventImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(EventModel, on_delete=models.CASCADE)
    name = models.ImageField(upload_to=get_file_path_event ,max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

class ApplyEventModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, editable=False)
    event = models.ForeignKey(EventModel, on_delete=models.CASCADE,blank=True, editable=False)
    is_confirm = models.BooleanField(default=False,blank=True, editable=False)

    def __str__(self):
        return self.name


class SeatsEventModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, editable=False)
    event = models.OneToOneField(EventModel, on_delete=models.CASCADE,blank=True, editable=False)
    total_seats = models.IntegerField(blank=True, editable=False)
    available_seats=models.IntegerField(blank=True, editable=False)

    def __str__(self):
        return str(self.total_seats)

project/techei/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import SeatsEventModel,User,IndividualProfile,City,State,InstitutionProfile,EventModel,FestClubModel,FestImage,EventImage,ApplyEventModel
from django.forms.utils import ValidationError
from django.db import models

TYPE=[
    ('','------Select-----'),
    ('0','Student'),
    ('1','Professional'),
    ('3', 'Other')
]

class IndividualSignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')


    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_individual = True
        user.is_confirm = True
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class IndividualProfileForm(forms.ModelForm):
    type=forms.CharField(label='User Type', widget=forms.Select(choices=TYPE))

    class Meta:
        model = IndividualProfile
        fields = ('college','contact','location','state' ,'city','type','age',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')


class InstitutionSignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_institution = True
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class InstitutionProfileForm(forms.ModelForm):
    class Meta:
        model = InstitutionProfile
        fields = ('institutionname','contact','location','regno','state' ,'city',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')


class AddEventForm(forms.ModelForm):
    class Meta:
        model = EventModel
        fields = ('title', 'description', 'venue', 'address', 'time', 'start_date', 'end_date', 'seats' ,'fee' ,'prize', 'paylink', 'fest', 'state', 'city', 'category', 'attendee_type')
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['city'].queryset = City.objects.none()

            if 'state' in self.data:
                try:
                    state_id = int(self.data.get('state'))
                    self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
            elif self.instance.pk:
                self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

class AddFestClubForm(forms.ModelForm):

    class Meta:
        model = FestClubModel
        fields = ('name', 'description')



class FestImageForm(forms.ModelForm):
    class Meta:
        model = FestImage
        fields = ('name', )

class EventImageForm(forms.ModelForm):
    class Meta:
        model = EventImage
        fields = ('name', )

class ApplyEventForm(forms.ModelForm):
    class Meta:
        model = ApplyEventModel
        fields = '__all__'


class SeatsEventForm(forms.ModelForm):
    class Meta:
        model = SeatsEventModel
        fields = '__all__'

project/techei/views/individual.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.views.generic import TemplateView,ListView, CreateView, UpdateView
from django.http import HttpResponse
from ..models import User,IndividualProfile,InstitutionProfile,City,State,EventModel,EventImage,Category,ApplyEventModel,SeatsEventModel
from django.urls import reverse_lazy
from ..forms import IndividualProfileForm,IndividualSignUpForm,ApplyEventForm,SeatsEventForm


class IndividualSignUpView(CreateView):
    model = User
    form_class = IndividualSignUpForm
    template_name = 'individual/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Individual'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/individual_profile')


def IndividualProfileView(request):
    if request.method == "POST":
        form=IndividualProfileForm(request.POST)
        if form.is_valid() :
            profile = form.save(commit = False)
            profile.user_id=request.user.id
            profile.save()
            return redirect('/')

    else:
        form = IndividualProfileForm()
    return render(request, "individual/profile.html",{"form":form})

def load_cities(request):
    state_id = request.GET.get('state')
    cities = City.objects.filter(state_id=state_id).order_by('name')
    return render(request, 'individual/city_drop_list.html', {'cities': cities})


# def IndividualDashboardView(request):
#     return render(request,'individual/individual_home.html')


def ApplyEvent(request, event_id):
    print(event_id)
    uid=request.user.id
    ev_type=EventModel.objects.get(id=event_id)
    evimg=EventImage.objects.filter(event_id=event_id)
    evinst=InstitutionProfile.objects.get(user_id=ev_type.user_id)
    city=City.objects.get(id=ev_type.city_id)
    state=State.objects.get(id=ev_type.state_id)
    category=Category.objects.get(id=ev_type.category_id)
    check=ApplyEventModel.objects.filter(event_id=ev_type.id,user_id=uid)
    sev=SeatsEventModel.objects.get(event_id=event_id)
    upcoming = EventModel.objects.all().order_by('start_date')[:3]
    inst_pro = User.objects.get(id=uid)
    clen=len(check)
    print(upcoming)
    if request.method == "POST":
        form=ApplyEventForm(request.POST)
        if form.is_valid():
            apply = form.save(commit = False)
            apply.user_id=request.user.id
            apply.event_id=event_id
            if ev_type.fee == 0:
                apply.is_confirm == True
            if not check:
                apply.save()
                a=int(sev.available_seats)
                a=a-1
                sev.available_seats=a
                sev.save()
            else:
                print("error")
            #return redirect('/techei/eventimage/')
        else:
            print(form.errors)
    else:
        form = ApplyEventForm()
    return render(request, "individual/applyevent.html",{"form":form,"event_id":event_id,"evimg":evimg,"evinst":evinst,"ev_type":ev_type,"city":city,"state":state,"category":category,"sev":sev,"clen":clen,"upcoming":upcoming,"inst_pro":inst_pro})

project/templates/individual/city_drop_list.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

project/templates/individual/individual_home.html
{% extends 'individual_base.html' %}

project/templates/individual/profile.html
{% load static %}
  <!-- <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Sign up as a {{ user_type }}</h2>
      <form method="post" id="profileForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form.as_table }}
        <button type="submit" class="btn btn-success">Sign up</button>
      </form>
    </div>
  </div> -->

<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Profile</title>

    <!-- Icons font CSS-->
    <link href="{% static "techei/profile/vendor/mdi-font/css/material-design-iconic-font.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "techei/profile/vendor/font-awesome-4.7/css/font-awesome.min.css" %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="{% static "https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static "techei/profile/vendor/select2/select2.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "techei/profile/vendor/datepicker/daterangepicker.css" rel="stylesheet" %}" media="all">

    <!-- Main CSS-->
    <link href="{% static "techei/profile/css/main.css" %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-red p-t-180 p-b-100 font-robo">
        <div class="wrapper wrapper--w960">
            <div class="card card-2">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title">Complete Your Profile</h2>
                    <form method="POST" id="profileForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>{% csrf_token %}
                        <input type="hidden" name="next" value="{{next}}">
                        <div class="input-group">
                            <input class="input--style-2" type="text" placeholder="College Name" name="college" id="id_college" maxlength="50">
                        </div>
                        <div class="input-group">
                            <input class="input--style-2" type="text" placeholder="Contact" name="contact" id="id_contact" maxlength="15">
                        </div>

                        <label for="id_state">State:</label>
                        {{ form.state }}
                        <label for="id_city">Cty:</label>
                        {{ form.city }}
                        <br>

                        <div class="input-group">
                            <input class="input--style-2" type="text" placeholder="Location" name="location" id="id_location" maxlength="15">
                        </div>



                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <div class="rs-select2 js-select-simple select--no-search">
                                        {{ form.type}}
                                        <div class="select-dropdown"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="input-group">
                            <input class="input--style-2" type="number" placeholder="Age" name="age" id="id_age">
                        </div>


                        <div class="p-t-30">
                            <button class="btn btn--radius btn--green" type="submit">Finish</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static "techei/profile/vendor/jquery/jquery.min.js" %}"></script>
    <!-- Vendor JS-->
    <script src="{% static "techei/profile/vendor/select2/select2.min.js" %}" %}"></script>
    <script src="{% static "techei/profile/vendor/datepicker/moment.min.js" %}"></script>
    <script src="{% static "techei/profile/vendor/datepicker/daterangepicker.js" %}"></script>

    <!-- Main JS-->
    <script src="{% static "techei/profile/js/global.js" %}"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
      $("#id_state").change(function () {
        var url = $("#profileForm").attr("data-cities-url");
        var stateId = $(this).val();

        $.ajax({
          url: url,
          data: {
            'state': stateId
          },
          success: function (data) {
            $("#id_city").html(data);
          }
        });

      });
    </script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

project/templates/individual/signup_form.html
<!-- {% block content %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Sign up as a {{ user_type }}</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{form.as_table}}
        <button type="submit" class="btn btn-success">Sign up</button>
      </form>
    </div>
  </div>
{% endblock %}

 -->


{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Signup</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static "techei/signup/images/icons/favicon.ico" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/vendor/bootstrap/css/bootstrap.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/fonts/iconic/css/material-design-iconic-font.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/vendor/animate/animate.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/vendor/css-hamburgers/hamburgers.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/vendor/animsition/css/animsition.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/vendor/select2/select2.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/vendor/daterangepicker/daterangepicker.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/css/util.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "techei/signup/css/main.css" %}">
<!--===============================================================================================-->
</head>
<body style="background-color: #999999;">

	<div class="limiter">
		<div class="container-login100">
			<div class="login100-more" style="background-image: url('https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Flaurencoleman%2Ffiles%2F2019%2F05%2F191_jeu_stage_one_digital_transformation_chapter_2_rometty_014-1200x799.jpg');"></div>

			<div class="wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50">
				<form method="post" class="login100-form validate-form">{% csrf_token %}
					<input type="hidden" name="next" value="">
					<span class="login100-form-title p-b-59">
						<h2>Sign up as a {{ user_type }}</h2>
					</span>

					<div class="wrap-input100 validate-input" data-validate="Username is required">
						<span class="label-input100">Username</span>
						<br>
						{% if form.username.help_text %}
						<small style="color: grey">{{ form.username.help_text }}</small>
						{% endif %}
						{% for error in form.username.errors %}
						<p style="color: red">{{ error }}</p>
						{% endfor %}
						<br>
						<input class="input100" type="text" name="username" maxlength="150" id="id_username" placeholder="Name...">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Required">
						<span class="label-input100">First Name</span>
						<br>
						<input class="input100" type="text" name="first_name" id="id_first_name" maxlength="30" placeholder="First Name...">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Required">
						<span class="label-input100">Last Name</span
							<br>
							<br>
							<input class="input100" type="text" name="last_name" id="id_last_name" maxlength="30" placeholder="Last Name...">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						<br>
						{% if form.password1.help_text %}
						<small style="color: grey">{{ form.password1.help_text }}</small>
						{% endif %}
						{% for error in form.password1.errors %}
						<p style="color: red">{{ error }}</p>
						{% endfor %}
						<br>
						<input class="input100" type="password" name="password1" id="id_password1" placeholder="*************">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Repeat Password is required">
						<span class="label-input100">Repeat Password</span>
						<br>
						{% if form.password2.help_text %}
						<small style="color: grey">{{ form.password2.help_text }}</small>
						{% endif %}
						{% for error in form.password2.errors %}
						<p style="color: red">{{ error }}</p>
						{% endfor %}
						<br>
					  <input class="input100" type="password" name="password2" id="id_password2" placeholder="*************">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<span class="label-input100">Email</span>
						<br>
						<input class="input100" type="email" name="email" id="id_email" placeholder="Email addess...">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" type="submit">
								Next
							</button>
						</div>

						<a href="/accounts/login/" class="dis-block txt3 hov1 p-r-30 p-t-10 p-b-10 p-l-30">
							Sign in
							<i class="fa fa-long-arrow-right m-l-5"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

<!--===============================================================================================-->
	<script src="{% static "techei/signup/vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "techei/signup/vendor/animsition/js/animsition.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "techei/signup/vendor/bootstrap/js/popper.js" %}"></script>
	<script src="{% static "techei/signup/vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "techei/signup/vendor/select2/select2.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "techei/signup/vendor/daterangepicker/moment.min.js" %}"></script>
	<script src="{% static "techei/signup/vendor/daterangepicker/daterangepicker.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "techei/signup/vendor/countdowntime/countdowntime.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "techei/signup/js/main.js" %}"></script>

</body>
</html>