project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from techei.views import register,institution,individual
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('', register.HomeView, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('techei/', include('techei.urls')),
    path('accounts/signup/', register.SignUpView.as_view(), name='signup'),
    path('accounts/login/', register.LoginView.as_view(), name='login'),
    path('accounts/login/home/', register.HomeView, name='home'),
    path('accounts/signup/individual/', individual.IndividualSignUpView.as_view(), name='individual_signup'),
    path('accounts/signup/institution/', institution.InstitutionSignUpView.as_view(), name='institution_signup'),
    path('individual_profile', individual.IndividualProfileView, name='individual_profile'),
    path('institution_profile', institution.InstitutionProfileView, name='institution_profile'),
    path('ajax/load-cities/', individual.load_cities, name='ajax_load_cities'),
    #path('individual_dashboard', individual.IndividualDashboardView, name='individual_dashboard'),
    #path('institution_dashboard', institution.InstitutionDashboardView, name='institution_dashboard'),
    path('accounts/signup/institution/', institution.InstitutionSignUpView.as_view(), name='institution_signup'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/techei/urls.py
from django.urls import path
from techei.views import register,institution,individual

urlpatterns =[
    path('eventtype', institution.EventType.as_view(), name='event_type'),
    path('addevent/<int:type>/', institution.AddEvent, name='add_event'),
    path('addfest/', institution.AddFestClubView, name='add_fest'),
    path('festimage/',institution.FestImageView, name='add_fest_image'),
    path('eventimage/',institution.EventImageView, name='add_event_image'),
    path('apply/<int:event_id>/', individual.ApplyEvent, name='apply_event'),
    path('response/',institution.ResponseView, name='response'),
    path('enrolledevents/',individual.EnrolledView, name='enrolled_events'),
]

project/techei/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
import os



# Create your models here.

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('fest/', filename)

def get_file_path_event(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('event/', filename)

class State(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class User(AbstractUser):
    is_individual = models.BooleanField(default=False)
    is_institution = models.BooleanField(default=False)
    is_confirm = models.BooleanField(default=False)


class IndividualProfile(models.Model):
    TYPE=(
        ('0','Student'),
        ('1','Professional'),
        ('2','Other'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    college = models.CharField(max_length=50)
    contact = models.CharField(max_length=15)
    location = models.CharField(max_length=15)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    type = models.CharField(max_length=50, choices=TYPE)
    age= models.IntegerField()

    def __str__(self):
        return self.user.username


class InstitutionProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    institutionname = models.CharField(max_length=50)
    contact = models.CharField(max_length=15)
    location = models.CharField(max_length=15)
    regno = models.IntegerField()
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    rating = models.IntegerField(null=True)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class FestClubModel(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class EventModel(models.Model):
    ATYPE=(
        (0,'Student'),
        (1,'Professional'),
        (2,'Other'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    venue = models.CharField(max_length=100)
    address = models.TextField(max_length=200)
    time = models.TimeField(max_length=15)
    start_date = models.DateField(max_length=15)
    end_date = models.DateField(max_length=15)
    seats = models.IntegerField()
    fee = models.IntegerField(null=True,blank=True)
    prize = models.IntegerField(null=True,blank=True)
    paylink = models.CharField(null=True,max_length=100,blank=True)
    fest = models.ForeignKey(FestClubModel, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    attendee_type = models.IntegerField(choices=ATYPE)
    event_type = models.IntegerField()

    def __str__(self):
        return self.title

class FestImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fest = models.ForeignKey(FestClubModel, on_delete=models.CASCADE)
    name = models.ImageField(upload_to=get_file_path ,max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class EventImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(EventModel, on_delete=models.CASCADE)
    name = models.ImageField(upload_to=get_file_path_event ,max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

class ApplyEventModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, editable=False)
    event = models.ForeignKey(EventModel, on_delete=models.CASCADE,blank=True, editable=False)
    is_confirm = models.BooleanField(default=False,blank=True, editable=False)

    def __str__(self):
        return self.name


class SeatsEventModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, editable=False)
    event = models.OneToOneField(EventModel, on_delete=models.CASCADE,blank=True, editable=False)
    total_seats = models.IntegerField(blank=True, editable=False)
    available_seats=models.IntegerField(blank=True, editable=False)

    def __str__(self):
        return str(self.total_seats)

project/techei/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import SeatsEventModel,User,IndividualProfile,City,State,InstitutionProfile,EventModel,FestClubModel,FestImage,EventImage,ApplyEventModel
from django.forms.utils import ValidationError
from django.db import models

TYPE=[
    ('','------Select-----'),
    ('0','Student'),
    ('1','Professional'),
    ('3', 'Other')
]

class IndividualSignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')


    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_individual = True
        user.is_confirm = True
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class IndividualProfileForm(forms.ModelForm):
    type=forms.CharField(label='User Type', widget=forms.Select(choices=TYPE))

    class Meta:
        model = IndividualProfile
        fields = ('college','contact','location','state' ,'city','type','age',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')


class InstitutionSignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_institution = True
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class InstitutionProfileForm(forms.ModelForm):
    class Meta:
        model = InstitutionProfile
        fields = ('institutionname','contact','location','regno','state' ,'city',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')


class AddEventForm(forms.ModelForm):
    class Meta:
        model = EventModel
        fields = ('title', 'description', 'venue', 'address', 'time', 'start_date', 'end_date', 'seats' ,'fee' ,'prize', 'paylink', 'fest', 'state', 'city', 'category', 'attendee_type')
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['city'].queryset = City.objects.none()

            if 'state' in self.data:
                try:
                    state_id = int(self.data.get('state'))
                    self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
            elif self.instance.pk:
                self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

class AddFestClubForm(forms.ModelForm):

    class Meta:
        model = FestClubModel
        fields = ('name', 'description')



class FestImageForm(forms.ModelForm):
    class Meta:
        model = FestImage
        fields = ('name', )

class EventImageForm(forms.ModelForm):
    class Meta:
        model = EventImage
        fields = ('name', )

class ApplyEventForm(forms.ModelForm):
    class Meta:
        model = ApplyEventModel
        fields = '__all__'


class SeatsEventForm(forms.ModelForm):
    class Meta:
        model = SeatsEventModel
        fields = '__all__'

project/templates/institution/addevent.html
{% extends 'institution_base.html' %}
{% load static %}
{% block content %}
<head>
<title>Add Fest/Club</title>
<link href="{% static "techei/addfest/css/main.css" %}" rel="stylesheet" media="all">
</head>

<section class="home-slider owl-carousel">
      <div class="slider-item" style="background-image:url(/static/techei/dash/images/fest.jpg);">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row no-gutters slider-text align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-md-6 ftco-animate">
            <h1 class="mb-4">Add Workshops </h1>
            <p>Add your Workshops Here </p>
            <p><a href="#" class="btn btn-primary px-4 py-3 mt-3">Contact Us</a></p>
          </div>
        </div>
        </div>
      </div>
      <div class="slider-item" style="background-image:url(/static/techei/dash/images/club.png);">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row no-gutters slider-text align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-md-6 ftco-animate">
            <h1 class="mb-4">Add Competions</h1>
            <p>Add your Competitions Here </p>
            <p><a href="#" class="btn btn-primary px-4 py-3 mt-3">Contact Us</a></p>
          </div>
        </div>
        </div>
      </div>
    </section>

    <div class="page-wrapper bg-dark p-t-100 p-b-50">
        <div class="wrapper wrapper--w900">
            <div class="card card-6">

                <div class="card-body">
                  {% if not fest %}

                    <div class="card-footer">
                          <h1 class="mb-4">You Dont Have Any Clubs/Fest Registered. Register One To continue.</h1>
                        <a class="btn btn--radius-2 btn--blue-2" href="{% url 'add_fest' %}">Add Fest/Clubs</a>
                    </div>
                  {% endif %}
                  {% if fest %}
                  <form method="POST" id="event" data-cities-url="{% url 'ajax_load_cities' %}" >
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}">
                    <div class="form-row">
                        <div class="name">Fest/Club Name</div>
                        <div class="value">
                            <select class="input--style-6" name="fest" required id="id_fest">
                              <option  value="" selected="selected">---SELECT---</option>
                               {% for f in fest %}
                                <option value="{{f.id}}">{{f.name}}</option>
                               {% endfor %}
                              </select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">Category</div>
                        <div class="value">
                          {{form.category}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">Required Attendee Type</div>
                        {{form.attendee_type}}
                    </div>
                    <div class="form-row">
                      <div class="name">Title</div>
                      <div class="value">
                        <input class="input--style-6" type="text" name="title" required id="id_title">
                      </div>
                    </div>
                    <div class="form-row">
                        <div class="name">Venue</div>
                        <div class="value">
                            <input class="input--style-6" type="text" name="venue" required id="venue">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">Address</div>
                        <div class="value">
                            <div class="input-group">
                                <textarea class="textarea--style-6" name="address" id="id_address" placeholder="Provide the address" required></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="name">State</div>
                      {{form.state}}
                    </div>
                    <div class="form-row">
                        <div class="name">City</div>
                        {{form.city}}
                    </div>
                    <div class="form-row">
                        <div class="name">Time</div>
                        <div class="value">
                            <input class="input--style-6" type="time" name="time" required id="id_time">
                        </div>
                        {{form.time.errors}}
                    </div>
                    <div class="form-row">
                        <div class="name">Start Date</div>
                        <div class="value">
                            <input class="input--style-6" type="date" name="start_date" required id="id_start_date">
                        </div>
                        {{form.start_date.errors}}
                    </div>
                    <div class="form-row">
                        <div class="name">End Date</div>
                        <div class="value">
                            <input class="input--style-6" type="date" name="end_date" required id="id_end_date">
                        </div>
                        {{form.end_date.errors}}
                    </div>
                    <div class="form-row">
                        <div class="name">Seats</div>
                        <div class="value">
                            <input class="input--style-6" type="text" name="seats" required id="id_seats">
                        </div>
                        {{form.seats.errors}}
                    </div>
                    <div class="form-row">
                        <div class="name">Description</div>
                        <div class="value">
                            <div class="input-group">
                                <textarea class="textarea--style-6" name="description" id="id_description" placeholder="Describe the event"></textarea>
                            </div>
                        </div>
                    </div>
                    {% if type == 1 or type == 2 %}
                    <div class="form-row">
                        <div class="name">Fee</div>
                        <div class="value">
                            <input class="input--style-6" type="number" name="fee" id="id_fee">
                        </div>
                        {{form.fee.errors}}
                    </div>
                    <div class="form-row">
                        <div class="name">Payment Link</div>
                        <div class="value">
                            <input class="input--style-6" type="text" name="paylink" id="id_paylink">
                        </div>
                    </div>
                    {% endif %}
                    {% if type == 2 %}
                    <div class="form-row">
                        <div class="name">Prize</div>
                        <div class="value">
                            <input class="input--style-6" type="number" name="prize" id="id_prize">
                        </div>
                    </div>
                    {% endif %}
                    <div class="card-footer">
                        <button class="btn btn--radius-2 btn--blue-2"  type="submit">Next</button>
                    </div>
                  </form>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
          {{sform.errors}}


<!-- <div class="row">
  <div class="col-md-8 col-sm-10 col-12">
    <h2>Sign up as a {{ user_type }}</h2>
    <form method="post" id="event" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ next }}">
      {{ sform.as_table }}
      <button type="submit" class="btn btn-success">Sign up</button>
    </form>
  </div>
</div> -->

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_state").change(function () {
    var url = $("#event").attr("data-cities-url");
    var stateId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'state': stateId
      },
      success: function (data) {
        $("#id_city").html(data);
      }
    });

  });
</script>

{% endblock %}

project/templates/institution/addfestclub.html
{% extends 'institution_base.html' %}
{% load static %}
{% block content %}
<head>
<title>Add Fest/Club</title>
<link href="{% static "techei/addfest/css/main.css" %}" rel="stylesheet" media="all">
</head>
<section class="home-slider owl-carousel">
      <div class="slider-item" style="background-image:url(/static/techei/dash/images/fest.jpg);">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row no-gutters slider-text align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-md-6 ftco-animate">
            <h1 class="mb-4">Add Fest </h1>
            <p>Add your Fest </p>
            <!-- <p><a href="#" class="btn btn-primary px-4 py-3 mt-3">Contact Us</a></p> -->
          </div>
        </div>
        </div>
      </div>
      <div class="slider-item" style="background-image:url(/static/techei/dash/images/club.png);">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row no-gutters slider-text align-items-center justify-content-start" data-scrollax-parent="true">
          <div class="col-md-6 ftco-animate">
            <h1 class="mb-4">Add</h1>
            <!-- <p><a href="#" class="btn btn-primary px-4 py-3 mt-3">Contact Us</a></p> -->
          </div>
        </div>
        </div>
      </div>
    </section>

    <div class="page-wrapper bg-dark p-t-100 p-b-50">
        <div class="wrapper wrapper--w900">
            <div class="card card-6">

                <div class="card-body">
                    <form method="POST" id="event">  {% csrf_token %}
                        <div class="form-row">
                            <div class="name">Fest/Club Name</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="name" required id="id_name">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="name">Description</div>
                            <div class="value">
                                <div class="input-group">
                                    <textarea class="textarea--style-6" name="description" id="id_description" placeholder="Description about your event"></textarea>
                                </div>
                            </div>
                        </div>

                </div>
                <div class="card-footer">
                    <button class="btn btn--radius-2 btn--blue-2" type="submit">Next</button>
                </div>
             </form>
            </div>
        </div>
    </div>

    <section class="ftco-section bg-light">
<h1 class="mb-4">My Fest and Clubs </h1>
			<div class="container">
				<div class="row">
          {% for fc in fim%}
          <div class="col-md-6 col-lg-4 ftco-animate">
            <div class="blog-entry">
                  <a href="blog-single.html" class="block-20 d-flex align-items-end" style="background-image: url('{{fc.name.url}}');">
                  </a>
              <div class="text bg-white p-4">
                <h3 class="heading"><a href="#">{{fc.fest.name}}</a></h3>
                <div class="d-flex align-items-center mt-4">
	                <p class="mb-0"><a href="#" class="btn btn-primary">Events<span class="ion-ios-arrow-round-forward"></span></a></p>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
			</div>
		</section>



<!-- <div class="row">
  <div class="col-md-8 col-sm-10 col-12">
    <h2>Sign up as a</h2>
    <form method="post" id="event" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ next }}">
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">Add</button>
    </form>
  </div>
</div> -->
<script src="{% static "techei/addfest/vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "techei/addfest/js/global.js"  %}"></script>
{% endblock %}

project/templates/institution/profile.html
{% load static %}
  <!-- <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Sign up as a {{ user_type }}</h2>
      <form method="post" id="profileForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form.as_table }}
        <button type="submit" class="btn btn-success">Sign up</button>
      </form>
    </div>
  </div> -->

  <!DOCTYPE html>
  <html lang="en">

  <head>
      <!-- Required meta tags-->
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="Colorlib Templates">
      <meta name="author" content="Colorlib">
      <meta name="keywords" content="Colorlib Templates">

      <!-- Title Page-->
      <title>Profile</title>

      <!-- Icons font CSS-->
      <link href="{% static "techei/profile/vendor/mdi-font/css/material-design-iconic-font.min.css" %}" rel="stylesheet" media="all">
      <link href="{% static "techei/profile/vendor/font-awesome-4.7/css/font-awesome.min.css" %}" rel="stylesheet" media="all">
      <!-- Font special for pages-->
      <link href="{% static "https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

      <!-- Vendor CSS-->
      <link href="{% static "techei/profile/vendor/select2/select2.min.css" %}" rel="stylesheet" media="all">
      <link href="{% static "techei/profile/vendor/datepicker/daterangepicker.css" rel="stylesheet" %}" media="all">

      <!-- Main CSS-->
      <link href="{% static "techei/profile/css/main.css" %}" rel="stylesheet" media="all">
  </head>

  <body>
      <div class="page-wrapper bg-red p-t-180 p-b-100 font-robo">
          <div class="wrapper wrapper--w960">
              <div class="card card-2">
                  <div class="card-heading"></div>
                  <div class="card-body">
                      <h2 class="title">Complete Your Profile</h2>
                      <form method="POST" id="addevent" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>{% csrf_token %}
                          <input type="hidden" name="next" value="{{next}}">
                          <div class="input-group">
                              <input class="input--style-2" type="text" placeholder="Institution/Company Name" name="institutionname" id="id_institutionname" maxlength="50">
                          </div>
                          <div class="input-group">
                              <input class="input--style-2" type="text" placeholder="Contact" name="contact" id="id_contact" maxlength="15">
                          </div>
                          <label for="id_state">State:</label>
                          {{form.state }}

                          <label for="id_city">Cty:</label>
                          {{form.city }}
                          <br>
                          <div class="input-group">
                              <input class="input--style-2" type="text" placeholder="Location" name="location" id="id_location" maxlength="15">
                          </div>
                          <div class="input-group">
                              <input class="input--style-2" type="number" placeholder="Registration Number" name="regno" id="id_regno">
                          </div>



                          <!-- <div class="row row-space">
                              <div class="col-2">
                                  <div class="input-group">
                                      <div class="rs-select2 js-select-simple select--no-search">

                                          <div class="select-dropdown"></div>
                                      </div>
                                  </div>-
                              </div>
                          </div> -->
                          <!-- <div class="input-group">
                              <div class="rs-select2 js-select-simple select--no-search">

                                  <div class="select-dropdown"></div>
                              </div>
                          </div> -->

                          <div class="p-t-30">
                              <button class="btn btn--radius btn--green" type="submit">Finish</button>
                          </div>
                      </form>
                  </div>
              </div>
          </div>
      </div>

      <!-- Jquery JS-->
      <script src="{% static "techei/profile/vendor/jquery/jquery.min.js" %}"></script>
      <!-- Vendor JS-->
      <script src="{% static "techei/profile/vendor/select2/select2.min.js" %}" %}"></script>
      <script src="{% static "techei/profile/vendor/datepicker/moment.min.js" %}"></script>
      <script src="{% static "techei/profile/vendor/datepicker/daterangepicker.js" %}"></script>

      <!-- Main JS-->
      <script src="{% static "techei/profile/js/global.js" %}"></script>

      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script>
        $("#id_state").change(function () {
          var url = $("#addevent").attr("data-cities-url");
          var stateId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'state': stateId
            },
            success: function (data) {
              $("#id_city").html(data);
            }
          });

        });
      </script>

  </body><!-- This templates was made by Colorlib (https://colorlib.com) -->

  </html>
  <!-- end document-->